{
  "sha1": "ryck15sp56omt9czofzjbrmqu3ssvrv",
  "insertion": {
    "when": "2026-03-08T17:32:29.592Z",
    "url": "https://github.com/plantuml/plantuml/issues/1969",
    "user": "The-Lum"
  }
}
@startuml
{start1} a -> b++
{end1} return
{start1}<->{end1} : 10 seconds
@enduml
